Update makefile.yml

diff --git a/.github/workflows/makefile.yml b/.github/workflows/makefile.yml
--- a/.github/workflows/makefile.yml
+++ b/.github/workflows/makefile.yml
@@ -21,7 +21,7 @@ jobs:
         run: make
 
       - name: Verify executable
-        run: ls -l bin/fst || (echo "Executable not found!" && exit 1)
+        run: ls -l bin/oopf || (echo "Executable not found!" && exit 1)
 
       - name: Run Valgrind Memory Check
-        run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes bin/fst || (echo "Valgrind detected issues!" && exit 1)
+        run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes bin/oopf || (echo "Valgrind detected issues!" && exit 1)
